# Generated by Django 4.2.1 on 2023-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='autoservice/car_images', verbose_name='image'),
        ),
    ]
