# Generated by Django 4.2.1 on 2023-05-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='price',
        ),
    ]
