# Generated by Django 4.2.1 on 2023-06-06 10:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_order_due_back_alter_car_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='about_order',
            field=tinymce.models.HTMLField(default='Enter order decriptio', max_length=4000, verbose_name='Order description'),
        ),
    ]
