# Generated by Django 4.2.1 on 2023-06-07 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0004_order_about_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='about_order',
            field=tinymce.models.HTMLField(default='Enter order decription', max_length=4000, verbose_name='Order description'),
        ),
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_at', models.DateField(auto_now_add=True, verbose_name='messaged at')),
                ('message', models.TextField(max_length=4000, verbose_name='meesage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_chats', to='autoservice.order', verbose_name='order')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_chats', to='autoservice.orderline', verbose_name='order_line')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_chats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order chat',
                'verbose_name_plural': 'order chats',
                'ordering': ['-message_at'],
            },
        ),
    ]
