# Generated by Django 4.2.1 on 2023-06-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_alter_orderchat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderchat',
            name='order_line',
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='message',
            field=models.TextField(max_length=4000, verbose_name='meesage'),
        ),
    ]
